# Generated by Django 4.2.6 on 2023-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0004_alter_review_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='followers', to='movieApp.usuario'),
        ),
    ]
