# Generated by Django 4.2.6 on 2023-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_alter_usuario_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='genero',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='creditos',
            field=models.ManyToManyField(to='movieApp.cast'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(to='movieApp.genero'),
        ),
    ]
