# Generated by Django 4.2.6 on 2023-10-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0006_remove_cast_pelicula_remove_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='creditos',
            field=models.ManyToManyField(to='movieApp.actor'),
        ),
    ]
