# Generated by Django 4.2.6 on 2023-10-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0007_alter_pelicula_creditos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='apellido',
        ),
        migrations.AddField(
            model_name='actor',
            name='imgURL',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
