# Generated by Django 4.2.6 on 2023-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0008_remove_actor_apellido_actor_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
